//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.24 at 03:07:56 PM CDT 
//


package xyz.aizuchi.comicrack;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComicPageInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComicPageInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Image" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Type" type="{}ComicPageType" default="Story" />
 *       &lt;attribute name="DoublePage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ImageSize" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="Key" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="ImageWidth" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *       &lt;attribute name="ImageHeight" type="{http://www.w3.org/2001/XMLSchema}int" default="-1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComicPageInfo")
public class ComicPageInfo {

    @XmlAttribute(name = "Image", required = true)
    protected int image;
    @XmlAttribute(name = "Type")
    protected List<String> type;
    @XmlAttribute(name = "DoublePage")
    protected Boolean doublePage;
    @XmlAttribute(name = "ImageSize")
    protected Long imageSize;
    @XmlAttribute(name = "Key")
    protected String key;
    @XmlAttribute(name = "ImageWidth")
    protected Integer imageWidth;
    @XmlAttribute(name = "ImageHeight")
    protected Integer imageHeight;

    /**
     * Gets the value of the image property.
     * 
     */
    public int getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     */
    public void setImage(int value) {
        this.image = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getType() {
        if (type == null) {
            type = new ArrayList<String>();
        }
        return this.type;
    }

    /**
     * Gets the value of the doublePage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDoublePage() {
        if (doublePage == null) {
            return false;
        } else {
            return doublePage;
        }
    }

    /**
     * Sets the value of the doublePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDoublePage(Boolean value) {
        this.doublePage = value;
    }

    /**
     * Gets the value of the imageSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getImageSize() {
        if (imageSize == null) {
            return  0L;
        } else {
            return imageSize;
        }
    }

    /**
     * Sets the value of the imageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setImageSize(Long value) {
        this.imageSize = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        if (key == null) {
            return "";
        } else {
            return key;
        }
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the imageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getImageWidth() {
        if (imageWidth == null) {
            return -1;
        } else {
            return imageWidth;
        }
    }

    /**
     * Sets the value of the imageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setImageWidth(Integer value) {
        this.imageWidth = value;
    }

    /**
     * Gets the value of the imageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getImageHeight() {
        if (imageHeight == null) {
            return -1;
        } else {
            return imageHeight;
        }
    }

    /**
     * Sets the value of the imageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setImageHeight(Integer value) {
        this.imageHeight = value;
    }

}
